from __future__ import annotations

import json
import random
from pathlib import Path


COLUMNS = [
    ("zoonotic", "Zoonotic", "mark"),
    ("other_reservoirs", "Other reservoirs", "text"),
    ("asymptomatic", "Asymptomatic", "mark"),
    ("wildlife_reservoir", "Wildlife reservoir", "mark"),
    ("animal_to_animal", "Animal to animal", "mark"),
    ("transplacental", "Transplacental", "mark"),
    ("venereal", "Venereal", "mark"),
    ("general_direct", "General (direct contact)", "mark"),
    ("people", "People", "mark"),
    ("animals", "Animals", "mark"),
    ("rodents", "Rodents", "mark"),
    ("fomites", "Fomites", "mark"),
    ("syringes_needles", "Syringes/needles", "mark"),
    ("feed", "Feed (ingestion)", "mark"),
    ("water", "Water (ingestion)", "mark"),
    ("general_inhalation", "General (inhalation)", "mark"),
    ("droplet", "Droplet (inhalation)", "mark"),
    ("aerosol", "Aerosol (inhalation)", "mark"),
    ("soil_manure", "Soil / Manure", "mark"),
    ("vector", "Vector", "mark"),
]

# Transcribed from the user-provided crop (References column excluded).
ROWS = [
    {
        "disease": "Enterotoxemia (Clostridium spp.)",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "Humans",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "X",
            "animals": "X",
            "rodents": "X",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Foot-and-mouth Disease",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "Cloven-hooved livestock, wildlife",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "X",
            "animals": "X",
            "rodents": "X",
            "fomites": "X",
            "syringes_needles": "X",
            "feed": "X",
            "water": "",
            "general_inhalation": "X",
            "droplet": "",
            "aerosol": "X",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "Giardiasis",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Mammals",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "X",
            "animals": "X",
            "rodents": "X",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Infectious Bovine Keratoconjunctivitis",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "",
            "asymptomatic": "X",
            "wildlife_reservoir": "",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "X",
            "animals": "X",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "X",
        },
    },
    {
        "disease": "Infectious Bovine Rhinotracheitis (IBR)",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "",
            "asymptomatic": "X",
            "wildlife_reservoir": "",
            "animal_to_animal": "X",
            "transplacental": "X",
            "venereal": "X",
            "general_direct": "X",
            "people": "X",
            "animals": "",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "",
            "water": "",
            "general_inhalation": "X",
            "droplet": "",
            "aerosol": "X",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "(Inter)digital infections",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "All",
            "asymptomatic": "",
            "wildlife_reservoir": "",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "",
            "syringes_needles": "",
            "feed": "",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Intestinal parasites",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Ruminants",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "X",
            "animals": "X",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Leptospirosis",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Mammals",
            "asymptomatic": "",
            "wildlife_reservoir": "",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "X",
            "general_direct": "X",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "X",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Lice and ectoparasites",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "",
            "asymptomatic": "",
            "wildlife_reservoir": "",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "",
            "animals": "X",
            "rodents": "X",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "Listeriosis",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Mammals, birds",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "X",
            "venereal": "",
            "general_direct": "X",
            "people": "X",
            "animals": "X",
            "rodents": "X",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "(Sub)clinical mastitis",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "",
            "asymptomatic": "X",
            "wildlife_reservoir": "",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "X",
            "animals": "",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "",
            "water": "",
            "general_inhalation": "X",
            "droplet": "",
            "aerosol": "X",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Metritis: trichomoniasis (T) + chlamydiosis (C)",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "",
            "asymptomatic": "",
            "wildlife_reservoir": "",
            "animal_to_animal": "T",
            "transplacental": "",
            "venereal": "T+C",
            "general_direct": "T",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "",
            "syringes_needles": "",
            "feed": "C",
            "water": "C",
            "general_inhalation": "C",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "Necrobacillosis (laryngitis)",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "",
            "asymptomatic": "X",
            "wildlife_reservoir": "",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "Neosporosis",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Mammals",
            "asymptomatic": "X",
            "wildlife_reservoir": "",
            "animal_to_animal": "",
            "transplacental": "X",
            "venereal": "",
            "general_direct": "",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "Papillomatosis",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "",
            "asymptomatic": "X",
            "wildlife_reservoir": "",
            "animal_to_animal": "X",
            "transplacental": "X",
            "venereal": "",
            "general_direct": "X",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "X",
        },
    },
    {
        "disease": "Paratuberculosis",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "Mammals",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "",
            "transplacental": "X",
            "venereal": "X",
            "general_direct": "",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "Q Fever / Coxiellosis",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Vertebrates",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "X",
            "venereal": "X",
            "general_direct": "X",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "X",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Rabies",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Mammals",
            "asymptomatic": "",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "",
            "animals": "X",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "X",
            "feed": "X",
            "water": "X",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "Salmonellosis",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "X",
            "animals": "X",
            "rodents": "X",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "X",
            "droplet": "",
            "aerosol": "X",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Scabies",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "",
            "asymptomatic": "",
            "wildlife_reservoir": "",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "Schmallenberg disease",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "Ruminants",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "",
            "transplacental": "X",
            "venereal": "X",
            "general_direct": "",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "",
            "syringes_needles": "",
            "feed": "",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "X",
        },
    },
    {
        "disease": "Tuberculosis (bovine)",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Mammals",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "",
            "transplacental": "X",
            "venereal": "",
            "general_direct": "X",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "X",
            "droplet": "X",
            "aerosol": "",
            "soil_manure": "X",
            "vector": "",
        },
    },
]

# Extra rows from the second cattle table crop (same schema, References excluded).
ROWS += [
    {
        "disease": "Anaplasmosis",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "Mammals, birds",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "",
            "transplacental": "X",
            "venereal": "",
            "general_direct": "X",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "",
            "syringes_needles": "X",
            "feed": "",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "X",
        },
    },
    {
        "disease": "Anthrax",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Mammals, birds",
            "asymptomatic": "X",
            "wildlife_reservoir": "",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "X",
            "vector": "X",
        },
    },
    {
        "disease": "Aujeszky's Disease",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "Pigs, sheep, dogs, cats, rodents, ...",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "X",
            "venereal": "X",
            "general_direct": "X",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "",
            "water": "X",
            "general_inhalation": "X",
            "droplet": "",
            "aerosol": "X",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Babesiosis (bovine)",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Buffaloes, deer",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "",
            "transplacental": "",
            "venereal": "",
            "general_direct": "",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "",
            "syringes_needles": "",
            "feed": "",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "X",
        },
    },
    {
        "disease": "Bluetongue",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "Ruminants, carnivores",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "X",
            "venereal": "X",
            "general_direct": "X",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "",
            "syringes_needles": "X",
            "feed": "",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "X",
        },
    },
    {
        "disease": "Botulism",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Most animals",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "X",
            "animals": "X",
            "rodents": "X",
            "fomites": "X",
            "syringes_needles": "X",
            "feed": "X",
            "water": "X",
            "general_inhalation": "X",
            "droplet": "",
            "aerosol": "X",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Bovine enzootic leucosis",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "",
            "asymptomatic": "X",
            "wildlife_reservoir": "",
            "animal_to_animal": "X",
            "transplacental": "X",
            "venereal": "",
            "general_direct": "X",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "",
            "syringes_needles": "X",
            "feed": "",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "X",
        },
    },
    {
        "disease": "Bovine herpesvirus 4",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "Ruminants",
            "asymptomatic": "X",
            "wildlife_reservoir": "",
            "animal_to_animal": "",
            "transplacental": "",
            "venereal": "X",
            "general_direct": "",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "X",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "Bovine respiratory disease*",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "Ruminants",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "X",
            "animals": "X",
            "rodents": "X",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "X",
            "droplet": "X",
            "aerosol": "X",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "Bovine Spongiform Encephalopathy",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Sheep, goats",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "",
            "transplacental": "X",
            "venereal": "",
            "general_direct": "",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "",
            "syringes_needles": "",
            "feed": "X",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "Bovine Viral Diarrhoea",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "",
            "asymptomatic": "X",
            "wildlife_reservoir": "",
            "animal_to_animal": "X",
            "transplacental": "X",
            "venereal": "X",
            "general_direct": "X",
            "people": "X",
            "animals": "X",
            "rodents": "X",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "",
            "general_inhalation": "X",
            "droplet": "",
            "aerosol": "X",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Brucellosis",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Ruminants, pigs, dogs, rodents, ...",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "X",
            "venereal": "X",
            "general_direct": "",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "X",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Campylobacteriosis",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Vertebrates",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "X",
            "general_direct": "X",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Coccidiosis",
        "values": {
            "zoonotic": "",
            "other_reservoirs": "",
            "asymptomatic": "X",
            "wildlife_reservoir": "",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "X",
            "animals": "",
            "rodents": "X",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Cryptosporidiosis",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Mammals",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "X",
            "animals": "X",
            "rodents": "X",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Cysticercosis",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "",
            "transplacental": "",
            "venereal": "",
            "general_direct": "",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "Dermatophytosis",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Mammals, birds",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "X",
        },
    },
    {
        "disease": "Diarrhoea / enteritis (coronavirus, rotavirus, E. coli)",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Mammals",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "X",
            "animals": "X",
            "rodents": "X",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Distomatosis",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Ruminants",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "",
            "transplacental": "",
            "venereal": "",
            "general_direct": "",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "",
            "syringes_needles": "",
            "feed": "X",
            "water": "",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "",
        },
    },
    {
        "disease": "E. Coli (verotoxic)",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Mammals",
            "asymptomatic": "",
            "wildlife_reservoir": "",
            "animal_to_animal": "X",
            "transplacental": "",
            "venereal": "",
            "general_direct": "X",
            "people": "X",
            "animals": "X",
            "rodents": "X",
            "fomites": "X",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "X",
            "vector": "",
        },
    },
    {
        "disease": "Echinococcosis",
        "values": {
            "zoonotic": "X",
            "other_reservoirs": "Mammals, birds",
            "asymptomatic": "X",
            "wildlife_reservoir": "X",
            "animal_to_animal": "",
            "transplacental": "",
            "venereal": "",
            "general_direct": "",
            "people": "",
            "animals": "",
            "rodents": "",
            "fomites": "",
            "syringes_needles": "",
            "feed": "X",
            "water": "X",
            "general_inhalation": "",
            "droplet": "",
            "aerosol": "",
            "soil_manure": "",
            "vector": "",
        },
    },
]

# The second (Anaplasmosis...Echinococcosis) crop is verified row-by-row against this
# reference sequence to prevent left/right half misalignment during manual transcription.
SECOND_TABLE_REFERENCES = [
    "[1-4]",
    "[5, 6]",
    "[4, 7]",
    "[4]",
    "[4, 7, 8]",
    "[9-19]",
    "[20-23]",
    "[24]",
    "[25-123]",
    "[4, 7, 124, 125]",
    "[48, 65, 126-137]",
    "[4, 7, 138-144]",
    "[4, 8]",
    "[145-160]",
    "[148, 150, 161-176]",
    "[4, 177, 178]",
    "[4, 179]",
    "[56, 59, 66, 67, 161, 165, 167, 170, 176, 180-199]",
    "[21, 200, 201]",
    "[202-212]",
    "[4, 213, 214]",
]

VALUE_LABEL = {
    "": "nincs jelölve",
    "X": "X jelölés",
    "T": "T jelölés",
    "C": "C jelölés",
    "T+C": "T+C jelölés",
}


def build_text_options(correct_value: str, rng: random.Random) -> list[str]:
    normalized = [row["values"]["other_reservoirs"] or "Nincs külön megadva" for row in ROWS]
    all_values = sorted(set(normalized))
    correct = correct_value or "Nincs külön megadva"
    distractors = [item for item in all_values if item != correct]
    picks = rng.sample(distractors, 3)
    options = [correct, *picks]
    rng.shuffle(options)
    return options


def build_options_from_columns(row: dict, col_key: str, value: str, rng: random.Random) -> list[str] | None:
    candidates = []
    for key, label, kind in COLUMNS:
        if kind != "mark" or key == col_key:
            continue
        if row["values"][key] != value:
            candidates.append(label)
    if len(candidates) < 3:
        return None
    picks = rng.sample(candidates, 3)
    col_label = next(label for key, label, _ in COLUMNS if key == col_key)
    options = [col_label, *picks]
    rng.shuffle(options)
    return options


def build_options_from_rows(col_key: str, correct_disease: str, value: str, rng: random.Random) -> list[str] | None:
    candidates = []
    for row in ROWS:
        if row["disease"] == correct_disease:
            continue
        if row["values"][col_key] != value:
            candidates.append(row["disease"])
    if len(candidates) < 3:
        return None
    picks = rng.sample(candidates, 3)
    options = [correct_disease, *picks]
    rng.shuffle(options)
    return options


def generate_questions() -> list[dict]:
    questions = []
    qid = 1

    for r_idx, row in enumerate(ROWS):
        disease = row["disease"]
        for c_idx, (col_key, col_label, kind) in enumerate(COLUMNS):
            value = row["values"][col_key]
            rng = random.Random((r_idx + 1) * 1000 + (c_idx + 1) * 19)

            if kind == "text":
                options_text = build_text_options(value, rng)
                options = [{"id": i + 1, "text": text} for i, text in enumerate(options_text)]
                correct_text = value or "Nincs külön megadva"
                correct_id = next(item["id"] for item in options if item["text"] == correct_text)
                prompt = f'A táblázat alapján a(z) "{disease}" sorban mi szerepel az "{col_label}" oszlopban?'
                tags = [f"row:{disease}", f"col:{col_label}", f"cell:{disease}|{col_label}", "ask:text"]
            else:
                value_label = VALUE_LABEL[value]
                col_options = build_options_from_columns(row, col_key, value, rng)
                if col_options is not None:
                    options = [{"id": i + 1, "text": text} for i, text in enumerate(col_options)]
                    correct_id = next(item["id"] for item in options if item["text"] == col_label)
                    prompt = (
                        f'A táblázat alapján a(z) "{disease}" sorban melyik oszlopra igaz, hogy "{value_label}"?'
                    )
                    tags = [f"row:{disease}", f"cell:{disease}|{col_label}", "ask:column"]
                else:
                    row_options = build_options_from_rows(col_key, disease, value, rng)
                    if row_options is None:
                        raise RuntimeError(
                            f"Nem tudtam 4 opciót képezni: row={disease!r}, col={col_label!r}, value={value!r}"
                        )
                    options = [{"id": i + 1, "text": text} for i, text in enumerate(row_options)]
                    correct_id = next(item["id"] for item in options if item["text"] == disease)
                    prompt = (
                        f'A táblázat alapján a(z) "{col_label}" oszlopban melyik betegségre igaz, hogy "{value_label}"?'
                    )
                    tags = [f"col:{col_label}", f"cell:{disease}|{col_label}", "ask:row"]

            questions.append(
                {
                    "id": f"cattle-cell-{qid:03d}",
                    "topic": "all-cells",
                    "prompt": prompt,
                    "type": "single",
                    "difficulty": "medium",
                    "options": options,
                    "answers": [correct_id],
                    "tags": tags,
                }
            )
            qid += 1

    return questions


def main() -> None:
    second_start = next(i for i, row in enumerate(ROWS) if row["disease"] == "Anaplasmosis")
    second_rows = ROWS[second_start:]
    if len(second_rows) != len(SECOND_TABLE_REFERENCES):
        raise RuntimeError(
            f"Soreltolodas-ellenorzes hiba: masodik tabla sorainak szama ({len(second_rows)}) "
            f"nem egyezik a referencia oszlop elemeivel ({len(SECOND_TABLE_REFERENCES)})."
        )

    out = Path("data/cattle-transmission-topic.js")
    questions = generate_questions()

    pack = {
        "id": "cattle-transmission-table-pack",
        "title": "Szarvasmarha: Betegségek és terjedési utak",
        "course": "Járványtan",
        "version": "1.0.0",
        "topics": [
            {"id": "all", "label": "Minden kérdés"},
            {"id": "all-cells", "label": "Minden cella"},
        ],
        "questions": questions,
    }

    js = "window.QUIZ_PACKS = window.QUIZ_PACKS || [];\n\n"
    js += "window.QUIZ_PACKS.push("
    js += json.dumps(pack, ensure_ascii=False, indent=2)
    js += ");\n"
    out.write_text(js, encoding="utf-8")
    print(f"Pack kész: {out} (kérdések: {len(questions)})")


if __name__ == "__main__":
    main()
